version: "3.8"
services:
  app:
    container_name: api
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=core
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - safa
    command: npm run dev

  db:
    container_name: database
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: core
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - safa
volumes:
  db-data:
networks:
  safa:
